### ISSUE TITLE
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by Xiaolong-RRL** [UMass-Foundation-Model/3D-LLM#34]
Dear author:

Thanks for your interesting work.

When I run finetune on `finetune_scanqa.yaml` with scannet features, an error occured:

```
2023-10-12 21:41:15,670 [INFO] load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xl.pth

url_or_filename: /data/xxx/code/3d-llm/ckpts/pretrain_blip2_sam_flant5xl_v2.pth

2023-10-12 21:41:22,086 [INFO] number of trainable parameters: 372436480
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    main()
  File "train.py", line 108, in main
    runner.train()
  File "/data/renruilong/code/3d-llm/3DLLM_BLIP2-base/lavis/runners/runner_base.py", line 354, in train
    self._load_checkpoint(self.resume_ckpt_path)
  File "/data/renruilong/code/3d-llm/3DLLM_BLIP2-base/lavis/runners/runner_base.py", line 587, in _load_checkpoint
    self.optimizer.load_state_dict(checkpoint["optimizer"])
  File "/data/renruilong/miniconda3/envs/3dllm/lib/python3.8/site-packages/torch/optim/optimizer.py", line 390, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```

It seems like the `pretrain_blip2_sam_flant5xl_v2.pth` do not match the model defined in code, and I wonder how to solve this error?

Best!
Xiaolong

**Comment by jiuyouyun9** [comment]
Suggest to skip the optimizer parameter loading

**Comment by Xiaolong-RRL** [comment]
It works, Thanks a lot!!

**Comment by evelinehong** [comment]
resolved in https://github.com/UMass-Foundation-Model/3D-LLM/commit/f5cd275fa573eb428e09f49ff29e8dec6746faf4
Please also download the newest checkpoint

**Comment by Xiaolong-RRL** [comment]
I see, thanks a lot!!
