### ISSUE TITLE
The training goes error when you updated the 'blip2_t5.py' for optimizer parameters loading

### ISSUE THREAD

**Issue by jiuyouyun9** [UMass-Foundation-Model/3D-LLM#39]
When I run the training command 'python -m torch.distributed.run --nproc_per_node=8 train.py --cfg-path lavis/projects/blip2/train/pretrain.yaml', using the latest version, it goes error. The error information is listed below. I think the reason lies in  'blip2_t5.py' line 54-61, the newly added codes.
''
Traceback (most recent call last):
  File "train.py", line 111, in <module>
    main()
  File "train.py", line 107, in main
    runner.train()
  File "/root/3DLLM/3D-LLM-main-10.16/3DLLM_BLIP2-base/lavis/runners/runner_base.py", line 360, in train
    train_stats = self.train_epoch(cur_epoch)
  File "/root/3DLLM/3D-LLM-main-10.16/3DLLM_BLIP2-base/lavis/runners/runner_base.py", line 396, in train_epoch
    return self.task.train_epoch(
  File "/root/3DLLM/3D-LLM-main-10.16/3DLLM_BLIP2-base/lavis/tasks/base_task.py", line 110, in train_epoch
    return self._train_inner_loop(
  File "/root/3DLLM/3D-LLM-main-10.16/3DLLM_BLIP2-base/lavis/tasks/base_task.py", line 211, in _train_inner_loop
    loss = self.train_step(model=model, samples=samples)
  File "/root/3DLLM/3D-LLM-main-10.16/3DLLM_BLIP2-base/lavis/tasks/base_task.py", line 64, in train_step
    loss = model(samples)["loss"]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1026, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 1 2
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
''

**Comment by evelinehong** [comment]
Temporarily fixed in https://github.com/UMass-Foundation-Model/3D-LLM/tree/9717617bc7e68ad0e5a571c58774e7db64c042f9

(Might need to suppress warnings)
