### ISSUE TITLE
What if the point cloud features are not 1408 dimensional

### ISSUE THREAD

**Issue by Larerr** [UMass-Foundation-Model/3D-LLM#65]
Hi, thank you so much for your wonderful work and for giving me a better understanding of VLM.

I would like to ask, when running the code `3DLLM_BLIP2-base/inference.py` I found that if I input my own point cloud into it (the number of features per point is not 1408), it will not work. Upon inspection, the code `3DLLM_BLIP2-base/lavis/models/blip2_models/blip2_t5.py` makes heavy use of the number 1407 for parameter determination.

I'm wondering what I should do if I want to pass my own point cloud in and run it. (I'm worried that the rest of the code will also have a lot of 1407 that I won't be able to change all the way around)

**Comment by Larerr** [comment]
Sorry, I understand. I should preprocess my own point cloud data via `Three-step 3D Feature Extraction`.

**Comment by Larerr** [comment]
In `3D-LLM/3DLanguage_data/ChatCaptioner_based/gen_features/gen_scene_feat_blip.py`, it provides how to generate a 1408-dimensional point cloud, but how should I run `inference.py` if I already have a arbitrary-dimensional point cloud (eg. 3 dimensions-representing RGB respectively).

**Comment by Larerr** [comment]
And, whether the number of point clouds is fixed when loading the point cloud data, I found that the `mismatch `problem also occurs after modifying the number of point clouds. The error is reported as below:
```
Traceback (most recent call last):
  File "/data0/3D-LLM/3DLLM_BLIP2-base/correct.py", line 35, in <module>
    model.load_state_dict(checkpoint["model"], strict=False)
  File "/home/miniconda3/envs/3DLLM/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Blip2T5:
	size mismatch for t5_model.shared.weight: copying a param with shape torch.Size([64868, 2048]) from checkpoint, the shape in current model is torch.Size([52728, 2048]).
	size mismatch for t5_model.encoder.embed_tokens.weight: copying a param with shape torch.Size([64868, 2048]) from checkpoint, the shape in current model is torch.Size([52728, 2048]).
	size mismatch for t5_model.decoder.embed_tokens.weight: copying a param with shape torch.Size([64868, 2048]) from checkpoint, the shape in current model is torch.Size([52728, 2048]).
	size mismatch for t5_model.lm_head.weight: copying a param with shape torch.Size([64868, 2048]) from checkpoint, the shape in current model is torch.Size([52728, 2048]).
```
Very much looking forward to your reply!
