### ISSUE TITLE
OSError: Can't load tokenizer for 'bert-base-uncased'

### ISSUE THREAD

**Issue by AaronNZH** [UMass-Foundation-Model/3D-LLM#67]
I got the error following Quick Start: Inference

Traceback (most recent call last):
  File "inference.py", line 31, in <module>
    model = registry.get_model_class(model_cfg.arch).from_pretrained(model_type=model_cfg.model_type)
  File "/data/NZH/3D-LLM/3DLLM_BLIP2-base/lavis/models/base_model.py", line 68, in from_pretrained
    model = cls.from_config(model_cfg)
  File "/data/NZH/3D-LLM/3DLLM_BLIP2-base/lavis/models/blip2_models/blip2_t5.py", line 400, in from_config
    model = cls(
  File "/data/NZH/3D-LLM/3DLLM_BLIP2-base/lavis/models/blip2_models/blip2_t5.py", line 52, in __init__
    self.tokenizer = self.init_tokenizer()
  File "/data/NZH/3D-LLM/3DLLM_BLIP2-base/lavis/models/blip2_models/blip2.py", line 32, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
  File "/home/ubuntu/anaconda3/envs/lavis/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1838, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by AaronNZH** [comment]
It seems to be a network problem
